services:
   web:
      image: web
      environment:
        - ALLOW_OVERRIDE=true
      ports:
        - "81:80"
      links:
        - db
      volumes:
        - ./app:/var/www/html/
        - ./mysqlcerts/ca-cert.pem:/etc/ssl/certs/ca-cert.pem

   db:
     image: mariadb:10.8.2
     restart: always
     volumes:
       - ./mysql:/var/lib/mysql
       - ./mysqlcerts:/etc/mysql/certs
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: admin
       MYSQL_PASSWORD: test
       MYSQL_DATABASE: database
     command: >
       --ssl-ca=/etc/mysql/certs/ca-cert.pem
       --ssl-cert=/etc/mysql/certs/server-cert.pem
       --ssl-key=/etc/mysql/certs/server-key.pem
     ports:
       - "8889:3306"

   phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     links:
       - db
     ports:
       - 8890:80
     environment:
       MYSQL_USER: admin
       MYSQL_PASSWORD: test
       MYSQL_DATABASE: database
