services:
  certgen:
    image: alpine/openssl
    container_name: certgen
    volumes:
      - ./mysqlcerts:/etc/mysql/certs
      - ./ssl/certs:/etc/ssl/certs
      - ./ssl/private:/etc/ssl/private
    entrypoint: >
      sh -c "
        mkdir -p /etc/mysql/certs &&
        cd /etc/mysql/certs &&
        
        # Generar CA si no existe
        if [ ! -f ca-cert.pem ]; then
          openssl genrsa 2048 > ca-key.pem &&
          openssl req -new -x509 -nodes -days 365 -key ca-key.pem \
            -out ca-cert.pem -subj '/CN=devCA'
        fi &&
        
        # Generar certificados del servidor MySQL
        if [ ! -f server-key.pem ]; then
          openssl genrsa 2048 > server-key.pem &&
          openssl req -new -key server-key.pem -out server.csr -subj '/CN=db' &&
          openssl x509 -req -in server.csr -CA ca-cert.pem -CAkey ca-key.pem \
            -CAcreateserial -out server-cert.pem -days 365
          rm -f ca-cert.srl server.csr
        fi &&
    
        mkdir -p /etc/ssl/certs &&
        cd /etc/ssl/certs &&
        
        # Solo generar si no existen
        if [ ! -f /etc/ssl/certs/server.crt ] || [ ! -f /etc/ssl/private/server.key ]; then
          mkdir -p /etc/ssl/private &&
          openssl req -x509 -newkey rsa:2048 -keyout /etc/ssl/private/server.key -out /etc/ssl/certs/server.crt \
            -days 365 -nodes -subj '/CN=localhost'
        fi"

  db:
    image: mariadb:10.11.6
    container_name: db_app
    depends_on:
      certgen:
        condition: service_completed_successfully
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqlcerts:/etc/mysql/certs
    command: >
      --ssl-ca=/etc/mysql/certs/ca-cert.pem
      --ssl-cert=/etc/mysql/certs/server-cert.pem
      --ssl-key=/etc/mysql/certs/server-key.pem
    ports:
      - "8889:3306"

  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    container_name: web_app
    depends_on:
      db:
        condition: service_started
      certgen:
        condition: service_completed_successfully
    ports:
      - "81:443"
    volumes:
      - ./app:/var/www/html/
      - ./mysqlcerts/ca-cert.pem:/etc/ssl/certs/ca-cert.pem
      - ./ssl/certs/server.crt:/etc/ssl/certs/server.crt
      - ./ssl/private/server.key:/etc/ssl/private/server.key
      - ./app/apache/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
    command: >
      bash -c "a2enmod ssl rewrite headers &&
               a2ensite default-ssl &&
               apache2-foreground"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: phpmyadmin_app
    depends_on:
      - db
    ports:
      - "8890:80"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database

